server {
    listen 80;
    server_name 16.112.118.42;

    location / {
        include proxy_params;
        proxy_pass http://unix:/home/ubuntu/meditrack/meditrack.sock;
    }

    access_log /var/log/nginx/meditrack_access.log;
    error_log  /var/log/nginx/meditrack_error.log;
}
